import { describe, expect, it } from "vitest";

import {
  countVisibleRankedGames,
  countVisibleUnplayedGames,
  toHomeGameCards,
} from "./selectors";

describe("home-hub selectors", () => {
  const games = [
    {
      currentRank: null,
      key: "beat-match",
      metricValue: "0:55",
      name: "Beat Match",
      playCount: 2,
      recommendationText: "Combo rhythm lane",
      shortDescription: "Tap the highlighted lane in rhythm to build combo and clear the hit goal",
    },
    {
      currentRank: null,
      key: "chain-trigger",
      metricValue: "1:04",
      name: "Chain Trigger",
      playCount: 3,
      recommendationText: "Propagation logic sprint",
      shortDescription: "Arm a few helper nodes, then fire the source and let the graph propagate",
    },
    {
      currentRank: null,
      key: "icon-chain",
      metricValue: "1:08",
      name: "Icon Chain",
      playCount: 2,
      recommendationText: "Clue-led memory chain",
      shortDescription: "Read the reveal, then use the clue board to rebuild the hidden icon order from first to last",
    },
    {
      currentRank: null,
      key: "merge-climb",
      metricValue: "0:41",
      name: "Merge Climb",
      playCount: 2,
      recommendationText: "Growth-pressure merge board",
      shortDescription: "Merge matching tiles into a higher value while the board fills with new spawns after every move",
    },
    {
      currentRank: null,
      key: "relative-pitch",
      metricValue: "0:52",
      name: "Relative Pitch",
      playCount: 1,
      recommendationText: "Audio interval sprint",
      shortDescription: "Match the same pitch interval from a new base note across a short ear-training sprint",
    },
    {
      currentRank: 3,
      key: "color-sweep",
      metricValue: "0:42",
      name: "Color Sweep",
      playCount: 5,
      recommendationText: "Fastest improving",
      shortDescription: "Clear tiles",
    },
    {
      currentRank: null,
      key: "color-census",
      metricValue: "0:58",
      name: "Color Census",
      playCount: 2,
      recommendationText: "Rapid mosaic memory",
      shortDescription: "Read the full color spread",
    },
    {
      currentRank: null,
      key: "sudoku",
      metricValue: "No record yet",
      name: "Sudoku",
      playCount: 1,
      recommendationText: null,
      shortDescription: "Solve the grid",
    },
    {
      currentRank: null,
      key: "custom-mode",
      metricValue: "No record yet",
      name: "Custom Mode",
      playCount: 0,
      recommendationText: null,
      shortDescription: "Experimental",
    },
    {
      currentRank: null,
      key: "flip-match",
      metricValue: "1:12",
      name: "Flip Match",
      playCount: 3,
      recommendationText: "Board transformation sprint",
      shortDescription: "Flip the live board into the target silhouette",
    },
    {
      currentRank: null,
      key: "spot-change",
      metricValue: "1:05",
      name: "Spot Change",
      playCount: 2,
      recommendationText: "Fresh comparison board",
      shortDescription: "Find every difference",
    },
    {
      currentRank: null,
      key: "rotate-align",
      metricValue: "0:59",
      name: "Rotate Align",
      playCount: 5,
      recommendationText: "Route rotation sprint",
      shortDescription: "Reconnect the path between start and end",
    },
    {
      currentRank: null,
      key: "position-lock",
      metricValue: "1:03",
      name: "Position Lock",
      playCount: 4,
      recommendationText: "Spatial memory sprint",
      shortDescription: "Place each token back onto its remembered final cell",
    },
    {
      currentRank: null,
      key: "phase-lock",
      metricValue: "0:57",
      name: "Phase Lock",
      playCount: 3,
      recommendationText: "Sequential timing puzzle",
      shortDescription: "Lock each rotating wheel while its marker sits inside the target band",
    },
    {
      currentRank: null,
      key: "sync-pulse",
      metricValue: "0:49",
      name: "Sync Pulse",
      playCount: 2,
      recommendationText: "Dual-ring rhythm sync",
      shortDescription: "Tap when both pulse rings collapse into the same beat",
    },
    {
      currentRank: null,
      key: "glow-cycle",
      metricValue: "0:50",
      name: "Glow Cycle",
      playCount: 2,
      recommendationText: "Visual rhythm crest",
      shortDescription: "Tap the highlighted node only while the full pulse board crests together",
    },
    {
      currentRank: null,
      key: "tempo-hold",
      metricValue: "1:01",
      name: "Tempo Hold",
      playCount: 1,
      recommendationText: "Release timing ladder",
      shortDescription: "Hold, then release when the meter reaches the target duration",
    },
    {
      currentRank: null,
      key: "tap-safe",
      metricValue: "0:44",
      name: "Tap Safe",
      playCount: 6,
      recommendationText: "High-pressure filter drill",
      shortDescription: "Tap only the safe targets across short hazard waves",
    },
    {
      currentRank: null,
      key: "spinner-aim",
      metricValue: "0:52",
      name: "Spinner Aim",
      playCount: 5,
      recommendationText: "Angular timing drill",
      shortDescription: "Fire when the rotating launcher lines up with the target arc",
    },
    {
      currentRank: null,
      key: "sequence-point",
      metricValue: "0:54",
      name: "Sequence Point",
      playCount: 4,
      recommendationText: "Working memory sprint",
      shortDescription: "Replay the point sequence",
    },
    {
      currentRank: null,
      key: "hue-drift",
      metricValue: "0:47",
      name: "Hue Drift",
      playCount: 3,
      recommendationText: "Color inference sprint",
      shortDescription: "Fill the missing gradient step",
    },
    {
      currentRank: null,
      key: "tile-instant",
      metricValue: "1:07",
      name: "Tile Instant",
      playCount: 2,
      recommendationText: "Flash reconstruction sprint",
      shortDescription: "Memorize the board, then swap the live tiles back into the same arrangement",
    },
    {
      currentRank: null,
      key: "zone-lock",
      metricValue: "0:58",
      name: "Zone Lock",
      playCount: 2,
      recommendationText: "Overlapping zone puzzle",
      shortDescription: "Toggle shared cells until every zone card reaches its target lock count",
    },
    {
      currentRank: null,
      key: "tempo-weave",
      metricValue: "0:53",
      name: "Tempo Weave",
      playCount: 3,
      recommendationText: "Dual-lane rhythm split",
      shortDescription: "Track both lanes and tap each one only while its marker crosses the center target zone",
    },
    {
      currentRank: null,
      key: "cascade-clear",
      metricValue: "1:02",
      name: "Cascade Clear",
      playCount: 1,
      recommendationText: "Trigger-driven combo board",
      shortDescription: "Choose a row or column trigger that creates the biggest refill cascade and pushes the score target over the line",
    },
    {
      currentRank: null,
      key: "box-fill",
      metricValue: "1:06",
      name: "Box Fill",
      playCount: 2,
      recommendationText: "Tap-first packing board",
      shortDescription: "Pack an irregular box with a small tray of pieces, using rotation and anchor previews to avoid wasted fits",
    },
    {
      currentRank: null,
      key: "bubble-spawn",
      metricValue: "0:48",
      name: "Bubble Spawn",
      playCount: 2,
      recommendationText: "Growth-pressure field loop",
      shortDescription: "Manage a live bubble field where growth pulses and chain bursts compete for space and stability",
    },
    {
      currentRank: null,
      key: "line-connect",
      metricValue: "1:11",
      name: "Line Connect",
      playCount: 2,
      recommendationText: "Segment-first path builder",
      shortDescription: "Connect node pairs with touch-safe segments, using undo and resets when a route blocks the board",
    },
    {
      currentRank: null,
      key: "block-tessellate",
      metricValue: "1:09",
      name: "Block Tessellate",
      playCount: 2,
      recommendationText: "Gravity placement sprint",
      shortDescription: "Rotate and slide a falling piece queue so each silhouette is sealed without resetting the board",
    },
  ];

  it("counts ranked and unplayed games from visible cards", () => {
    expect(countVisibleRankedGames(games)).toBe(1);
    expect(countVisibleUnplayedGames(games)).toBe(1);
  });

  it("builds home cards with preview and status metadata", () => {
    expect(toHomeGameCards(games)).toEqual([
      {
        ...games[0],
        previewAlt: "Beat Match lane board with a center hit zone and three rhythm lanes",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/beat-match-preview.svg",
        recordLabel: "Best 0:55",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[1],
        previewAlt: "Chain Trigger graph board with a source node, armed helper node, and propagation links",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/chain-trigger-preview.svg",
        recordLabel: "Best 1:04",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[2],
        previewAlt: "Icon Chain clue board with a revealed icon strip and card-like order clues",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/icon-chain-preview.svg",
        recordLabel: "Best 1:08",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[3],
        previewAlt: "Merge Climb number board with directional controls, a goal tile, and a next spawn panel",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/merge-climb-preview.svg",
        recordLabel: "Best 0:41",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[4],
        previewAlt: "Relative Pitch panel with replay controls and four candidate pads around a current round prompt",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/relative-pitch-preview.svg",
        recordLabel: "Best 0:52",
        runLabel: "1 runs",
        statusLabel: "Played",
      },
      {
        ...games[5],
        previewAlt: "Color Sweep board showing a target swatch and a grid of colored tiles",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/color-sweep-preview.svg",
        recordLabel: "Best 0:42",
        runLabel: "5 runs",
        statusLabel: "Rank #3",
      },
      {
        ...games[6],
        previewAlt: "Color Census mosaic with a hidden query asking which color appeared most",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/color-census-preview.svg",
        recordLabel: "Best 0:58",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[7],
        previewAlt: "Sudoku puzzle board with preset digits and empty cells",
        previewObjectPosition: "top center",
        previewSrc: "/images/games/sudoku-preview.png",
        recordLabel: "No record",
        runLabel: "1 runs",
        statusLabel: "Played",
      },
      {
        ...games[8],
        previewAlt: null,
        previewObjectPosition: undefined,
        previewSrc: null,
        recordLabel: "No record",
        runLabel: "First run",
        statusLabel: "New",
      },
      {
        ...games[9],
        previewAlt: "Flip Match target and live card boards linked by a horizontal flip rule",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/flip-match-preview.svg",
        recordLabel: "Best 1:12",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[10],
        previewAlt: "Spot Change original and changed scene boards with one highlighted difference",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/spot-change-preview.svg",
        recordLabel: "Best 1:05",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[11],
        previewAlt: "Rotate Align path board with rotatable route tiles between start and end",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/rotate-align-preview.svg",
        recordLabel: "Best 0:59",
        runLabel: "5 runs",
        statusLabel: "Played",
      },
      {
        ...games[12],
        previewAlt: "Position Lock board with labeled tokens returning to remembered final cells",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/position-lock-preview.svg",
        recordLabel: "Best 1:03",
        runLabel: "4 runs",
        statusLabel: "Played",
      },
      {
        ...games[13],
        previewAlt: "Phase Lock wheel stack with rotating markers and glowing target bands",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/phase-lock-preview.svg",
        recordLabel: "Best 0:57",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[14],
        previewAlt: "Sync Pulse dual ring board with two pulse circles collapsing into a shared sync pad",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/sync-pulse-preview.svg",
        recordLabel: "Best 0:49",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[15],
        previewAlt: "Glow Cycle node grid with a highlighted target orb and a shared sync meter",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/glow-cycle-preview.svg",
        recordLabel: "Best 0:50",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[16],
        previewAlt: "Tempo Hold meter board with a glowing target zone and a long hold bar",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/tempo-hold-preview.svg",
        recordLabel: "Best 1:01",
        runLabel: "1 runs",
        statusLabel: "Played",
      },
      {
        ...games[17],
        previewAlt: "Tap Safe wave board mixing safe targets and hazard objects with short-lived badges",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/tap-safe-preview.svg",
        recordLabel: "Best 0:44",
        runLabel: "6 runs",
        statusLabel: "Played",
      },
      {
        ...games[18],
        previewAlt: "Spinner Aim ring with a rotating launcher, target arc, and hazard arc",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/spinner-aim-preview.svg",
        recordLabel: "Best 0:52",
        runLabel: "5 runs",
        statusLabel: "Played",
      },
      {
        ...games[19],
        previewAlt: "Sequence Point grid showing a fast memory sequence across lit points",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/sequence-point-preview.svg",
        recordLabel: "Best 0:54",
        runLabel: "4 runs",
        statusLabel: "Played",
      },
      {
        ...games[20],
        previewAlt: "Hue Drift gradient row with a missing color step and answer swatches",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/hue-drift-preview.svg",
        recordLabel: "Best 0:47",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[21],
        previewAlt: "Tile Instant target memory board next to a shuffled live reconstruction board",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/tile-instant-preview.svg",
        recordLabel: "Best 1:07",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[22],
        previewAlt: "Zone Lock puzzle board with overlapping zone cards and lock-count targets",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/zone-lock-preview.svg",
        recordLabel: "Best 0:58",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[23],
        previewAlt: "Tempo Weave dual-lane rhythm board with independent lane markers and center hit zones",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/tempo-weave-preview.svg",
        recordLabel: "Best 0:53",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[24],
        previewAlt: "Cascade Clear board with row and column trigger rails surrounding a color token grid",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/cascade-clear-preview.svg",
        recordLabel: "Best 1:02",
        runLabel: "1 runs",
        statusLabel: "Played",
      },
      {
        ...games[25],
        previewAlt: "Box Fill tray-and-board puzzle with selected polyomino pieces and a highlighted anchor preview",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/box-fill-preview.svg",
        recordLabel: "Best 1:06",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[26],
        previewAlt: "Bubble Spawn field with growing colored bubbles, dual pressure meters, and a highlighted best burst target",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/bubble-spawn-preview.svg",
        recordLabel: "Best 0:48",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[27],
        previewAlt: "Line Connect grid with labeled node pairs, an active route, and a step-by-step path build",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/line-connect-preview.svg",
        recordLabel: "Best 1:11",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[28],
        previewAlt: "Block Tessellate silhouette board with a falling piece queue, ghost landing cells, and hard-drop controls",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/block-tessellate-preview.svg",
        recordLabel: "Best 1:09",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
    ]);
  });
});
