import { describe, expect, it } from "vitest";

import {
  countVisibleRankedGames,
  countVisibleUnplayedGames,
  toHomeGameCards,
} from "./selectors";

describe("home-hub selectors", () => {
  const games = [
    {
      currentRank: 3,
      key: "color-sweep",
      metricValue: "0:42",
      name: "Color Sweep",
      playCount: 5,
      recommendationText: "Fastest improving",
      shortDescription: "Clear tiles",
    },
    {
      currentRank: null,
      key: "color-census",
      metricValue: "0:58",
      name: "Color Census",
      playCount: 2,
      recommendationText: "Rapid mosaic memory",
      shortDescription: "Read the full color spread",
    },
    {
      currentRank: null,
      key: "sudoku",
      metricValue: "No record yet",
      name: "Sudoku",
      playCount: 1,
      recommendationText: null,
      shortDescription: "Solve the grid",
    },
    {
      currentRank: null,
      key: "custom-mode",
      metricValue: "No record yet",
      name: "Custom Mode",
      playCount: 0,
      recommendationText: null,
      shortDescription: "Experimental",
    },
    {
      currentRank: null,
      key: "flip-match",
      metricValue: "1:12",
      name: "Flip Match",
      playCount: 3,
      recommendationText: "Board transformation sprint",
      shortDescription: "Flip the live board into the target silhouette",
    },
    {
      currentRank: null,
      key: "spot-change",
      metricValue: "1:05",
      name: "Spot Change",
      playCount: 2,
      recommendationText: "Fresh comparison board",
      shortDescription: "Find every difference",
    },
    {
      currentRank: null,
      key: "rotate-align",
      metricValue: "0:59",
      name: "Rotate Align",
      playCount: 5,
      recommendationText: "Route rotation sprint",
      shortDescription: "Reconnect the path between start and end",
    },
    {
      currentRank: null,
      key: "position-lock",
      metricValue: "1:03",
      name: "Position Lock",
      playCount: 4,
      recommendationText: "Spatial memory sprint",
      shortDescription: "Place each token back onto its remembered final cell",
    },
    {
      currentRank: null,
      key: "phase-lock",
      metricValue: "0:57",
      name: "Phase Lock",
      playCount: 3,
      recommendationText: "Sequential timing puzzle",
      shortDescription: "Lock each rotating wheel while its marker sits inside the target band",
    },
    {
      currentRank: null,
      key: "sync-pulse",
      metricValue: "0:49",
      name: "Sync Pulse",
      playCount: 2,
      recommendationText: "Dual-ring rhythm sync",
      shortDescription: "Tap when both pulse rings collapse into the same beat",
    },
    {
      currentRank: null,
      key: "tap-safe",
      metricValue: "0:44",
      name: "Tap Safe",
      playCount: 6,
      recommendationText: "High-pressure filter drill",
      shortDescription: "Tap only the safe targets across short hazard waves",
    },
    {
      currentRank: null,
      key: "spinner-aim",
      metricValue: "0:52",
      name: "Spinner Aim",
      playCount: 5,
      recommendationText: "Angular timing drill",
      shortDescription: "Fire when the rotating launcher lines up with the target arc",
    },
    {
      currentRank: null,
      key: "sequence-point",
      metricValue: "0:54",
      name: "Sequence Point",
      playCount: 4,
      recommendationText: "Working memory sprint",
      shortDescription: "Replay the point sequence",
    },
    {
      currentRank: null,
      key: "hue-drift",
      metricValue: "0:47",
      name: "Hue Drift",
      playCount: 3,
      recommendationText: "Color inference sprint",
      shortDescription: "Fill the missing gradient step",
    },
  ];

  it("counts ranked and unplayed games from visible cards", () => {
    expect(countVisibleRankedGames(games)).toBe(1);
    expect(countVisibleUnplayedGames(games)).toBe(1);
  });

  it("builds home cards with preview and status metadata", () => {
    expect(toHomeGameCards(games)).toEqual([
      {
        ...games[0],
        previewAlt: "Color Sweep board showing a target swatch and a grid of colored tiles",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/color-sweep-preview.svg",
        recordLabel: "Best 0:42",
        runLabel: "5 runs",
        statusLabel: "Rank #3",
      },
      {
        ...games[1],
        previewAlt: "Color Census mosaic with a hidden query asking which color appeared most",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/color-census-preview.svg",
        recordLabel: "Best 0:58",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[2],
        previewAlt: "Sudoku puzzle board with preset digits and empty cells",
        previewObjectPosition: "top center",
        previewSrc: "/images/games/sudoku-preview.png",
        recordLabel: "No record",
        runLabel: "1 runs",
        statusLabel: "Played",
      },
      {
        ...games[3],
        previewAlt: null,
        previewObjectPosition: undefined,
        previewSrc: null,
        recordLabel: "No record",
        runLabel: "First run",
        statusLabel: "New",
      },
      {
        ...games[4],
        previewAlt: "Flip Match target and live card boards linked by a horizontal flip rule",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/flip-match-preview.svg",
        recordLabel: "Best 1:12",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[5],
        previewAlt: "Spot Change original and changed scene boards with one highlighted difference",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/spot-change-preview.svg",
        recordLabel: "Best 1:05",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[6],
        previewAlt: "Rotate Align path board with rotatable route tiles between start and end",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/rotate-align-preview.svg",
        recordLabel: "Best 0:59",
        runLabel: "5 runs",
        statusLabel: "Played",
      },
      {
        ...games[7],
        previewAlt: "Position Lock board with labeled tokens returning to remembered final cells",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/position-lock-preview.svg",
        recordLabel: "Best 1:03",
        runLabel: "4 runs",
        statusLabel: "Played",
      },
      {
        ...games[8],
        previewAlt: "Phase Lock wheel stack with rotating markers and glowing target bands",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/phase-lock-preview.svg",
        recordLabel: "Best 0:57",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
      {
        ...games[9],
        previewAlt: "Sync Pulse dual ring board with two pulse circles collapsing into a shared sync pad",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/sync-pulse-preview.svg",
        recordLabel: "Best 0:49",
        runLabel: "2 runs",
        statusLabel: "Played",
      },
      {
        ...games[10],
        previewAlt: "Tap Safe wave board mixing safe targets and hazard objects with short-lived badges",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/tap-safe-preview.svg",
        recordLabel: "Best 0:44",
        runLabel: "6 runs",
        statusLabel: "Played",
      },
      {
        ...games[11],
        previewAlt: "Spinner Aim ring with a rotating launcher, target arc, and hazard arc",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/spinner-aim-preview.svg",
        recordLabel: "Best 0:52",
        runLabel: "5 runs",
        statusLabel: "Played",
      },
      {
        ...games[12],
        previewAlt: "Sequence Point grid showing a fast memory sequence across lit points",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/sequence-point-preview.svg",
        recordLabel: "Best 0:54",
        runLabel: "4 runs",
        statusLabel: "Played",
      },
      {
        ...games[13],
        previewAlt: "Hue Drift gradient row with a missing color step and answer swatches",
        previewObjectPosition: undefined,
        previewSrc: "/images/games/hue-drift-preview.svg",
        recordLabel: "Best 0:47",
        runLabel: "3 runs",
        statusLabel: "Played",
      },
    ]);
  });
});
