import type { SupportedArcadeLocale } from "./locale";
import { gameCatalogTranslations } from "./game-catalog.translations";

type CountSupportMetricSource = "hintCount" | "mistakeCount";

type CountSupportMetricDefinition = {
  kind: "count";
  label: string;
  noun: string;
  noteVerb: string;
  recoveryVerb: string;
  recoveryZeroNote: string;
  source: CountSupportMetricSource;
  zeroSummaryText: string;
  zeroNote: string;
};

type PrecisionDropRatingSupportMetricDefinition = {
  kind: "precision-drop-rating";
  label: "Hit rating";
};

type GameSupportMetricDefinition = CountSupportMetricDefinition | PrecisionDropRatingSupportMetricDefinition;

type GamePrimaryMetricDefinition = {
  bestLabel: string;
  completedLabel: string;
  direction: "lower-better";
  failedLabel: string;
  format: "duration_seconds" | "offset_px";
};

export const supportedGames = [
  {
    accentColor: "#14b8a6",
    homeTags: ["perception", "fast-start"],
    id: "game-color-sweep",
    key: "color-sweep",
    name: "Color Sweep",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Only the target color counts. Wrong taps lower quality, and timeouts stay in history only.",
    shortDescription: "Clear every tile that matches the target color before the timer expires.",
    storedKey: "COLOR_SWEEP",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong taps",
      noun: "wrong tap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect sweep kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong taps",
      zeroNote: "Perfect sweep",
    },
  },
  {
    accentColor: "#ec4899",
    homeTags: ["memory", "perception"],
    id: "game-color-census",
    key: "color-census",
    name: "Color Census",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Memorize the mosaic, answer the color-distribution query, and finish the sprint before the timer expires.",
    shortDescription: "Study a brief color mosaic, then answer which color dominated or how often one appeared.",
    storedKey: "COLOR_CENSUS",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistakes",
      noun: "mistake",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect census kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistakes",
      zeroNote: "Perfect census",
    },
  },
  {
    accentColor: "#ec4899",
    homeTags: ["timing", "rhythm"],
    id: "game-beat-match",
    key: "beat-match",
    name: "Beat Match",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Match the active lane on beat, build combo, and reach the hit goal before the stream ends or the timer expires.",
    shortDescription: "Tap the highlighted lane in rhythm to build combo and push the hit goal over the line.",
    storedKey: "BEAT_MATCH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Max combo",
      noun: "combo",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No combo recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no combo",
      zeroNote: "No combo",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["logic", "spatial"],
    id: "game-block-tessellate",
    key: "block-tessellate",
    name: "Block Tessellate",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Guide the falling queue into the target silhouette, use hard drops only when the lock is clean, and keep misdrops low before the timer expires.",
    shortDescription: "Rotate and slide a falling piece queue so each silhouette is sealed without resetting the board.",
    storedKey: "BLOCK_TESSELLATE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misdrops",
      noun: "misdrop",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero misdrops kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misdrops",
      zeroNote: "Zero misdrops",
    },
  },
  {
    accentColor: "#3b82f6",
    homeTags: ["logic", "spatial"],
    id: "game-bounce-angle",
    key: "bounce-angle",
    name: "Bounce Angle",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Read the bank shot, launch into the green pocket, and keep wasted shots low before the timer expires.",
    shortDescription: "Choose one fixed angle and let the side-wall ricochet carry the ball into the correct pocket.",
    storedKey: "BOUNCE_ANGLE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Shots used",
      noun: "shot",
      noteVerb: "used",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-shot preview kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no shots",
      zeroNote: "Zero shots",
    },
  },
  {
    accentColor: "#a855f7",
    homeTags: ["memory", "timing"],
    id: "game-cascade-flip",
    key: "cascade-flip",
    name: "Cascade Flip",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Memorize the reveal order, then track the moving stream and keep misses low before the timer expires.",
    shortDescription: "Watch a short reveal, then flip the same order out of a shifting card stream.",
    storedKey: "CASCADE_FLIP",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misses",
      noun: "miss",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect stream kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misses",
      zeroNote: "Perfect stream",
    },
  },
  {
    accentColor: "#16a34a",
    homeTags: ["reflex", "timing"],
    id: "game-gap-rush",
    key: "gap-rush",
    name: "Gap Rush",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Retarget the runner one lane at a time, let the glide settle before each wall arrives, and stay centered for perfect passes as the corridor speeds up.",
    shortDescription: "Guide a drifting runner through a fixed wall sequence by picking the next lane early enough to survive the speed ramp.",
    storedKey: "GAP_RUSH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Perfect passes",
      noun: "perfect pass",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No perfect passes kept in recovery.",
      source: "hintCount",
      zeroSummaryText: "no perfect passes",
      zeroNote: "No perfect passes",
    },
  },
  {
    accentColor: "#22c55e",
    homeTags: ["reflex", "logic"],
    id: "game-bubble-spawn",
    key: "bubble-spawn",
    name: "Bubble Spawn",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Burst the biggest pressure cluster before the next growth pulse lands, keep saturation below the field limit, and fill stability before the board overloads.",
    shortDescription: "Manage a live bubble field where growth pulses and chain bursts compete for space and stability.",
    storedKey: "BUBBLE_SPAWN",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Best chain",
      noun: "chain",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No chain recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no chain",
      zeroNote: "No chain",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["logic", "spatial"],
    id: "game-box-fill",
    key: "box-fill",
    name: "Box Fill",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Select a tray piece, rotate it into the right footprint, preview one anchor at a time, and pack the whole irregular box before the timer expires.",
    shortDescription: "Pack an irregular box with a small tray of pieces, using rotation and anchor previews to avoid wasted fits.",
    storedKey: "BOX_FILL",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Placement errors",
      noun: "placement error",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero placement errors kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no placement errors",
      zeroNote: "Zero placement errors",
    },
  },
  {
    accentColor: "#38bdf8",
    homeTags: ["logic", "spatial"],
    id: "game-line-connect",
    key: "line-connect",
    name: "Line Connect",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Build each route one segment at a time, keep every path from crossing the locked lanes, and finish the board set before the timer expires.",
    shortDescription: "Connect node pairs with touch-safe segments, using undo and resets when a route blocks the board.",
    storedKey: "LINE_CONNECT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Path corrections",
      noun: "correction",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero corrections kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no corrections",
      zeroNote: "Zero corrections",
    },
  },
  {
    accentColor: "#38bdf8",
    homeTags: ["logic", "spatial"],
    id: "game-chain-trigger",
    key: "chain-trigger",
    name: "Chain Trigger",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Arm the smallest useful helper set, fire the source, and solve each trigger graph before the timer expires.",
    shortDescription: "Plan a deterministic trigger chain by arming a few extra nodes before firing the source.",
    storedKey: "CHAIN_TRIGGER",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Extra triggers",
      noun: "extra trigger",
      noteVerb: "used",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero extra triggers kept in recovery.",
      source: "hintCount",
      zeroSummaryText: "no extra triggers",
      zeroNote: "Zero extra triggers",
    },
  },
  {
    accentColor: "#8b5cf6",
    homeTags: ["logic", "memory"],
    id: "game-icon-chain",
    key: "icon-chain",
    name: "Icon Chain",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Memorize the icon order, then rebuild the chain from anchor, slot, and order clues before the timer expires.",
    shortDescription: "Read the reveal, then use the clue board to rebuild the hidden icon order from first to last.",
    storedKey: "ICON_CHAIN",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong picks",
      noun: "wrong pick",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect chain kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong picks",
      zeroNote: "Perfect chain",
    },
  },
  {
    accentColor: "#f97316",
    homeTags: ["logic", "spatial"],
    id: "game-merge-climb",
    key: "merge-climb",
    name: "Merge Climb",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Slide the number board, combine matching tiles, and reach the goal value before the board locks up or the timer expires.",
    shortDescription: "Merge matching tiles into a higher value while the board fills with new spawns after every move.",
    storedKey: "MERGE_CLIMB",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves used",
      noun: "move",
      noteVerb: "used",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move preview kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero moves",
    },
  },
  {
    accentColor: "#7c3aed",
    homeTags: ["audio", "memory"],
    id: "game-relative-pitch",
    key: "relative-pitch",
    name: "Relative Pitch",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Listen to the reference jump, hear the new base note, and choose the candidate that recreates the same interval before the timer expires.",
    shortDescription: "Match the same pitch interval from a new base note across a short ear-training sprint.",
    storedKey: "RELATIVE_PITCH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Replays used",
      noun: "replay",
      noteVerb: "used",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero replays kept in recovery.",
      source: "hintCount",
      zeroSummaryText: "no replays",
      zeroNote: "Zero replays",
    },
  },
  {
    accentColor: "#06b6d4",
    homeTags: ["logic", "perception"],
    id: "game-cascade-clear",
    key: "cascade-clear",
    name: "Cascade Clear",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Fire one row or column trigger at a time, let the board collapse and refill, and chase a high-scoring chain before your trigger limit runs out.",
    shortDescription: "Choose a row or column trigger that creates the biggest refill cascade and pushes the score target over the line.",
    storedKey: "CASCADE_CLEAR",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Best cascade",
      noun: "cascade",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No cascade recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no cascade",
      zeroNote: "No cascade",
    },
  },
  {
    accentColor: "#ea580c",
    homeTags: ["fast-start", "logic"],
    id: "game-minesweeper",
    key: "minesweeper",
    name: "Minesweeper",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Reveal all safe tiles. Mistakes cost quality score and leaderboard points.",
    shortDescription: "Clear the board quickly while keeping mistakes low.",
    storedKey: "MINESWEEPER",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistakes",
      noun: "mistake",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Clean board kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistakes",
      zeroNote: "Clean board",
    },
  },
  {
    accentColor: "#3b82f6",
    homeTags: ["logic", "fast-start"],
    id: "game-number-chain",
    key: "number-chain",
    name: "Number Chain",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Only the next number advances the chain. Wrong taps lower quality, and timeouts stay in history only.",
    shortDescription: "Tap the shuffled numbers in ascending order before the timer expires.",
    storedKey: "NUMBER_CHAIN",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong taps",
      noun: "wrong tap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect chain kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong taps",
      zeroNote: "Perfect chain",
    },
  },
  {
    accentColor: "#7c3aed",
    homeTags: ["memory"],
    id: "game-pair-flip",
    key: "pair-flip",
    name: "Pair Flip",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Mismatched cards flip back after a short reveal. Timeouts stay in history only.",
    shortDescription: "Flip cards two at a time and match every symbol before the timer expires.",
    storedKey: "PAIR_FLIP",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mismatches",
      noun: "mismatch",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect memory kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mismatches",
      zeroNote: "Perfect memory",
    },
  },
  {
    accentColor: "#0f766e",
    homeTags: ["logic"],
    id: "game-sudoku",
    key: "sudoku",
    name: "Sudoku",
    primaryMetric: {
      bestLabel: "Best solve time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Finish the puzzle fast. Hints lower quality and can remove leaderboard eligibility.",
    shortDescription: "Complete the grid with as few hints and errors as possible.",
    storedKey: "SUDOKU",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Hints used",
      noun: "hint",
      noteVerb: "used",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No hints recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no hints",
      zeroNote: "No hints needed",
    },
  },
  {
    accentColor: "#8b5cf6",
    homeTags: ["memory", "rhythm"],
    id: "game-pattern-echo",
    key: "pattern-echo",
    name: "Pattern Echo",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Wrong inputs count against quality but do not stop the run. Timeouts stay in history only.",
    shortDescription: "Watch the pad sequence flash, then reproduce it in the exact same order.",
    storedKey: "PATTERN_ECHO",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong inputs",
      noun: "wrong input",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect recall kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong inputs",
      zeroNote: "Perfect recall",
    },
  },
  {
    accentColor: "#60a5fa",
    homeTags: ["memory", "fast-start"],
    id: "game-sequence-point",
    key: "sequence-point",
    name: "Sequence Point",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Watch the point sequence, replay it in order, and finish the full sprint before the timer expires.",
    shortDescription: "Replay a growing point sequence from memory before time runs out.",
    storedKey: "SEQUENCE_POINT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistakes",
      noun: "mistake",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect sequence kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistakes",
      zeroNote: "Perfect sequence",
    },
  },
  {
    accentColor: "#f97316",
    homeTags: ["timing", "fast-start"],
    id: "game-precision-drop",
    key: "precision-drop",
    name: "Precision Drop",
    primaryMetric: {
      bestLabel: "Best hit offset",
      completedLabel: "Hit offset",
      direction: "lower-better",
      failedLabel: "Miss offset",
      format: "offset_px",
    },
    rulesSummary: "A smaller hit offset scores better. Missed drops stay in history only and do not enter rankings.",
    shortDescription: "Tap when the falling ball overlaps the target line to keep the offset tiny.",
    storedKey: "DROP_LINE",
    successfulResultLabel: "hit",
    supportMetric: {
      kind: "precision-drop-rating",
      label: "Hit rating",
    },
  },
  {
    accentColor: "#06b6d4",
    homeTags: ["timing", "reflex"],
    id: "game-spinner-aim",
    key: "spinner-aim",
    name: "Spinner Aim",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Fire through the target arc, avoid the hazard arc, and keep bad shots low before the timer expires.",
    shortDescription: "Time each shot so the rotating launcher passes through the target arc instead of the hazard.",
    storedKey: "SPINNER_AIM",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Bad shots",
      noun: "bad shot",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect aim kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no bad shots",
      zeroNote: "Perfect aim",
    },
  },
  {
    accentColor: "#8b5cf6",
    homeTags: ["timing", "spatial"],
    id: "game-phase-lock",
    key: "phase-lock",
    name: "Phase Lock",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Lock each wheel inside its target band, keep timing errors low, and finish the full stack before the timer expires.",
    shortDescription: "Freeze each rotating wheel in sequence while its marker sits inside the target band.",
    storedKey: "PHASE_LOCK",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Timing errors",
      noun: "timing error",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect lock kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no timing errors",
      zeroNote: "Perfect lock",
    },
  },
  {
    accentColor: "#14b8a6",
    homeTags: ["timing", "rhythm"],
    id: "game-sync-pulse",
    key: "sync-pulse",
    name: "Sync Pulse",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Tap while both pulse rings overlap, chain every wave, and keep perfect syncs high before the timer expires.",
    shortDescription: "Read the dual pulse overlap and tap when both rings collapse into the same beat.",
    storedKey: "SYNC_PULSE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Perfect hits",
      noun: "perfect hit",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No perfect syncs recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no perfect hits",
      zeroNote: "No perfect syncs",
    },
  },
  {
    accentColor: "#22d3ee",
    homeTags: ["timing", "perception"],
    id: "game-glow-cycle",
    key: "glow-cycle",
    name: "Glow Cycle",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Watch the whole pulse board, wait for the shared crest, and tap only the highlighted node before the timer expires.",
    shortDescription: "Tap the highlighted node only while the full pulse board crests together.",
    storedKey: "GLOW_CYCLE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistimed taps",
      noun: "mistimed tap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect glow sync kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistimed taps",
      zeroNote: "Perfect glow sync",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["timing", "rhythm"],
    id: "game-tempo-hold",
    key: "tempo-hold",
    name: "Tempo Hold",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Hold to the target duration, release in the right zone, and finish every round before the timer expires.",
    shortDescription: "Press and hold, then release when the meter reaches the target tempo window.",
    storedKey: "TEMPO_HOLD",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Perfect releases",
      noun: "perfect release",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "No perfect releases recorded in recovery.",
      source: "hintCount",
      zeroSummaryText: "no perfect releases",
      zeroNote: "No perfect releases",
    },
  },
  {
    accentColor: "#f472b6",
    homeTags: ["timing", "rhythm"],
    id: "game-tempo-weave",
    key: "tempo-weave",
    name: "Tempo Weave",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Watch both lanes, hit each center zone on time, and keep the split-attention streak alive before the timer ends.",
    shortDescription: "Track two independent beat lanes and tap each one only while its marker crosses the center target zone.",
    storedKey: "TEMPO_WEAVE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misses",
      noun: "miss",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-miss weave kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misses",
      zeroNote: "Zero-miss weave",
    },
  },
  {
    accentColor: "#2563eb",
    homeTags: ["timing", "fast-start"],
    id: "game-orbit-tap",
    key: "orbit-tap",
    name: "Orbit Tap",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Hit the gate repeatedly before the timer expires. Misses lower quality, and timeouts stay in history only.",
    shortDescription: "Tap when the orbit marker crosses the gate and chain enough hits to clear the run.",
    storedKey: "ORBIT_TAP",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misses",
      noun: "miss",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Clean orbit kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misses",
      zeroNote: "Clean orbit",
    },
  },
  {
    accentColor: "#ef4444",
    homeTags: ["reflex", "timing"],
    id: "game-target-trail",
    key: "target-trail",
    name: "Target Trail",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Only the live target advances the trail. Misses lower quality, and timeouts stay in history only.",
    shortDescription: "Chase the active target across the board and finish the trail before the timer expires.",
    storedKey: "TARGET_TRAIL",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misses",
      noun: "miss",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect trail kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misses",
      zeroNote: "Perfect trail",
    },
  },
  {
    accentColor: "#10b981",
    homeTags: ["memory", "logic"],
    id: "game-path-recall",
    key: "path-recall",
    name: "Path Recall",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Watch the path, replay it in order, and keep wrong cells low before the timer expires.",
    shortDescription: "Memorize the highlighted path, then retrace it cell by cell from memory.",
    storedKey: "PATH_RECALL",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong cells",
      noun: "wrong cell",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Clean recall kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong cells",
      zeroNote: "Clean recall",
    },
  },
  {
    accentColor: "#14b8a6",
    homeTags: ["memory", "spatial"],
    id: "game-position-lock",
    key: "position-lock",
    name: "Position Lock",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Watch the tokens settle, rebuild the final layout from memory, and keep placement errors low before the timer expires.",
    shortDescription: "Memorize where moving tokens stop, then place each one back onto its final cell.",
    storedKey: "POSITION_LOCK",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Placement errors",
      noun: "placement error",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect placement kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no placement errors",
      zeroNote: "Perfect placement",
    },
  },
  {
    accentColor: "#6366f1",
    homeTags: ["memory", "perception"],
    id: "game-pulse-count",
    key: "pulse-count",
    name: "Pulse Count",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Count the pulses, answer quickly, and keep wrong answers low before the timer expires.",
    shortDescription: "Watch the signal pulse, then choose the right count across a short answer sprint.",
    storedKey: "PULSE_COUNT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong answers",
      noun: "wrong answer",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect count kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong answers",
      zeroNote: "Perfect count",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["logic", "fast-start"],
    id: "game-quick-sum",
    key: "quick-sum",
    name: "Quick Sum",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Solve each prompt fast. Wrong answers lower quality, and timeouts stay in history only.",
    shortDescription: "Clear a rapid run of arithmetic prompts by choosing the right answer each round.",
    storedKey: "QUICK_SUM",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong answers",
      noun: "wrong answer",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect sum kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong answers",
      zeroNote: "Perfect sum",
    },
  },
  {
    accentColor: "#38bdf8",
    homeTags: ["logic", "memory"],
    id: "game-mcp-primer",
    key: "mcp-primer",
    name: "MCP Primer",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Read the MCP study pages, answer the full quiz, and finish before the timer expires. Wrong answers count as mistakes but do not stop the run.",
    shortDescription: "A study-first quiz on MCP fundamentals, primitives, and transports based on the public documentation.",
    storedKey: "MCP_PRIMER",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistakes",
      noun: "mistake",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect primer kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistakes",
      zeroNote: "Perfect primer",
    },
  },
  {
    accentColor: "#06b6d4",
    homeTags: ["logic", "fast-start"],
    id: "game-sum-grid",
    key: "sum-grid",
    name: "Sum Grid",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Place the candidate numbers so every row and column hits its target. Reset grids lower quality, and timeouts stay in history only.",
    shortDescription: "Fill the grid with the candidate numbers so every row sum and column sum lands exactly on target.",
    storedKey: "SUM_GRID",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Resets",
      noun: "reset",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Clean solve kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no resets",
      zeroNote: "Clean solve",
    },
  },
  {
    accentColor: "#22c55e",
    homeTags: ["perception", "fast-start"],
    id: "game-symbol-hunt",
    key: "symbol-hunt",
    name: "Symbol Hunt",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Only the target symbol counts. Wrong taps lower quality, and timeouts stay in history only.",
    shortDescription: "Find every copy of the target symbol hidden in the noisy board before time runs out.",
    storedKey: "SYMBOL_HUNT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong taps",
      noun: "wrong tap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect hunt kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong taps",
      zeroNote: "Perfect hunt",
    },
  },
  {
    accentColor: "#facc15",
    homeTags: ["perception", "fast-start"],
    id: "game-hidden-find",
    key: "hidden-find",
    name: "Hidden Find",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Find the exact target motif in each crowded scene. False taps lower quality, and timeouts stay in history only.",
    shortDescription: "Pick the one exact motif hidden inside each dense scene of lookalikes before time runs out.",
    storedKey: "HIDDEN_FIND",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "False taps",
      noun: "false tap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect search kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no false taps",
      zeroNote: "Perfect search",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["perception", "logic"],
    id: "game-hue-drift",
    key: "hue-drift",
    name: "Hue Drift",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Read the color drift, choose the missing step, and finish the sprint before the timer expires.",
    shortDescription: "Infer the missing color step from a drifting gradient row before time runs out.",
    storedKey: "HUE_DRIFT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Mistakes",
      noun: "mistake",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect drift kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no mistakes",
      zeroNote: "Perfect drift",
    },
  },
  {
    accentColor: "#fb7185",
    homeTags: ["perception", "logic"],
    id: "game-spot-change",
    key: "spot-change",
    name: "Spot Change",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Compare the original and changed scenes, tap only the real differences, and finish before the timer expires.",
    shortDescription: "Compare two scene boards and tap every changed tile before time runs out.",
    storedKey: "SPOT_CHANGE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Misses",
      noun: "miss",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect comparison kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no misses",
      zeroNote: "Perfect comparison",
    },
  },
  {
    accentColor: "#f97316",
    homeTags: ["reflex", "perception"],
    id: "game-tap-safe",
    key: "tap-safe",
    name: "Tap Safe",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Filter each wave fast. Hazard taps and missed safe targets add penalties, and timeouts stay in history only.",
    shortDescription: "Tap only the safe targets while short-lived hazard waves pressure your reflexes.",
    storedKey: "TAP_SAFE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Penalties",
      noun: "penalty",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-penalty run kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no penalties",
      zeroNote: "Zero-penalty run",
    },
  },
  {
    accentColor: "#06b6d4",
    homeTags: ["logic"],
    id: "game-light-grid",
    key: "light-grid",
    name: "Light Grid",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Toggle the board into the target state. Extra moves lower quality, and timeouts stay in history only.",
    shortDescription: "Flip the light grid until the live board matches the target pattern.",
    storedKey: "LIGHT_GRID",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves",
      noun: "move",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move solve kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero-move solve",
    },
  },
  {
    accentColor: "#f59e0b",
    homeTags: ["logic", "spatial"],
    id: "game-flip-match",
    key: "flip-match",
    name: "Flip Match",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Flip one tile to toggle a horizontal strip, match every target board, and finish the sprint before the timer expires.",
    shortDescription: "Toggle the live card board until it matches each target silhouette in a short logic sprint.",
    storedKey: "FLIP_MATCH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Flips",
      noun: "flip",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-flip solve kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no flips",
      zeroNote: "Zero-flip solve",
    },
  },
  {
    accentColor: "#06b6d4",
    homeTags: ["logic", "spatial"],
    id: "game-rotate-align",
    key: "rotate-align",
    name: "Rotate Align",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Rotate the path tiles, connect start to end, and finish the full sprint before the timer expires.",
    shortDescription: "Restore the route by rotating path tiles until the start-to-end line is complete.",
    storedKey: "ROTATE_ALIGN",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Rotations",
      noun: "rotation",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-rotation solve kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no rotations",
      zeroNote: "Zero-rotation solve",
    },
  },
  {
    accentColor: "#a855f7",
    homeTags: ["logic", "spatial"],
    id: "game-tile-shift",
    key: "tile-shift",
    name: "Tile Shift",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Shift rows and columns into place. Extra moves lower quality, and timeouts stay in history only.",
    shortDescription: "Rotate rows and columns until the live pattern matches the target board.",
    storedKey: "TILE_SHIFT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves",
      noun: "move",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move shift kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero-move shift",
    },
  },
  {
    accentColor: "#2563eb",
    homeTags: ["logic", "spatial"],
    id: "game-swap-solve",
    key: "swap-solve",
    name: "Swap Solve",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Swap two tiles at a time until the live board matches the target. Extra swaps lower quality, and failed boards stay in history only.",
    shortDescription: "Restore the scrambled board by swapping pairs of tiles before the swap budget or timer runs out.",
    storedKey: "SWAP_SOLVE",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Swaps",
      noun: "swap",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-swap solve kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no swaps",
      zeroNote: "Zero-swap solve",
    },
  },
  {
    accentColor: "#14b8a6",
    homeTags: ["memory", "spatial"],
    id: "game-tile-instant",
    key: "tile-instant",
    name: "Tile Instant",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Memorize the board quickly, then rebuild the hidden target by swapping live tiles before the timer expires.",
    shortDescription: "Flash-memorize the target board, then swap tiles back into the same arrangement from memory.",
    storedKey: "TILE_INSTANT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves",
      noun: "move",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move reconstruction kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero-move reconstruction",
    },
  },
  {
    accentColor: "#38bdf8",
    homeTags: ["logic", "spatial"],
    id: "game-zone-lock",
    key: "zone-lock",
    name: "Zone Lock",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Toggle shared cells until every overlapping zone reaches its target count before the timer expires.",
    shortDescription: "Read the overlapping zone cards, then lock cells until every target count holds at once.",
    storedKey: "ZONE_LOCK",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Resets",
      noun: "reset",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-reset run kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no resets",
      zeroNote: "Zero-reset run",
    },
  },
  {
    accentColor: "#fb7185",
    homeTags: ["logic", "spatial"],
    id: "game-stack-sort",
    key: "stack-sort",
    name: "Stack Sort",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Sort the stacks fast. Extra moves lower quality, and timeouts stay in history only.",
    shortDescription: "Move the top token between stacks until each stack holds only one color.",
    storedKey: "STACK_SORT",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves",
      noun: "move",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move sort kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero-move sort",
    },
  },
  {
    accentColor: "#84cc16",
    homeTags: ["memory", "spatial"],
    id: "game-mirror-match",
    key: "mirror-match",
    name: "Mirror Match",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Mirror the target board quickly. Extra moves lower quality, and timeouts stay in history only.",
    shortDescription: "Rebuild the mirrored target pattern on the editable grid before the timer expires.",
    storedKey: "MIRROR_MATCH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Moves",
      noun: "move",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Zero-move mirror kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no moves",
      zeroNote: "Zero-move mirror",
    },
  },
  {
    accentColor: "#8b5cf6",
    homeTags: ["logic", "perception"],
    id: "game-shape-morph",
    key: "shape-morph",
    name: "Shape Morph",
    primaryMetric: {
      bestLabel: "Best clear time",
      completedLabel: "Clear time",
      direction: "lower-better",
      failedLabel: "Run time",
      format: "duration_seconds",
    },
    rulesSummary: "Read the visual transform rule, choose the next glyph fast, and keep wrong answers low before the timer expires.",
    shortDescription: "Predict the next transformed shape by reading how rotation, scale, or cuts change across the sequence.",
    storedKey: "SHAPE_MORPH",
    successfulResultLabel: "clear",
    supportMetric: {
      kind: "count",
      label: "Wrong answers",
      noun: "wrong answer",
      noteVerb: "recorded",
      recoveryVerb: "kept in recovery",
      recoveryZeroNote: "Perfect morph kept in recovery.",
      source: "mistakeCount",
      zeroSummaryText: "no wrong answers",
      zeroNote: "Perfect morph",
    },
  },
] as const satisfies ReadonlyArray<{
  accentColor: string;
  homeTags: readonly string[];
  id: string;
  key: string;
  name: string;
  primaryMetric: GamePrimaryMetricDefinition;
  rulesSummary: string;
  shortDescription: string;
  storedKey: string;
  successfulResultLabel: string;
  supportMetric: GameSupportMetricDefinition;
}>;

export function listPersistedGames() {
  return supportedGames.map((game) => ({
    key: game.storedKey,
    name: game.name,
    shortDescription: game.shortDescription,
    accentColor: game.accentColor,
    rulesSummary: game.rulesSummary,
  }));
}

export function getLocalizedGameShortDescription(gameKey: string, locale: SupportedArcadeLocale) {
  const definition = getGameDefinition(gameKey);

  if (!definition) {
    return gameKey;
  }

  return gameCatalogTranslations[definition.key]?.[locale]?.shortDescription ?? definition.shortDescription;
}

export function getLocalizedGameRulesSummary(gameKey: string, locale: SupportedArcadeLocale) {
  const definition = getGameDefinition(gameKey);

  if (!definition) {
    return gameKey;
  }

  return gameCatalogTranslations[definition.key]?.[locale]?.rulesSummary ?? definition.rulesSummary;
}

export type GameKey = (typeof supportedGames)[number]["key"];
export type StoredGameKey = (typeof supportedGames)[number]["storedKey"];
export type GameDefinition = (typeof supportedGames)[number];
export type GameLink = {
  href: string;
  key: GameKey;
  label: string;
};

const gameDefinitionByKey = new Map(supportedGames.map((game) => [game.key, game] as const));
const legacyRouteKeyByAlias = new Map<string, GameKey>([
  ["drop-ball", "precision-drop"],
  ["drop-line", "precision-drop"],
]);

export function isGameKey(value: string): value is GameKey {
  return gameDefinitionByKey.has(value as GameKey);
}

export function resolveGameKey(value: string): GameKey | null {
  const normalizedRouteKey = value.toLowerCase().replace(/_/g, "-");

  if (gameDefinitionByKey.has(normalizedRouteKey as GameKey)) {
    return normalizedRouteKey as GameKey;
  }

  return legacyRouteKeyByAlias.get(normalizedRouteKey) ?? null;
}

export function toStoredGameKey(gameKey: GameKey): StoredGameKey;
export function toStoredGameKey(gameKey: string): string;
export function toStoredGameKey(gameKey: string) {
  const resolvedGameKey = resolveGameKey(gameKey);

  if (!resolvedGameKey) {
    return gameKey.toUpperCase().replace(/-/g, "_");
  }

  return gameDefinitionByKey.get(resolvedGameKey)!.storedKey;
}

export function toRouteGameKey(gameKey: StoredGameKey): GameKey;
export function toRouteGameKey(gameKey: string): string;
export function toRouteGameKey(gameKey: string) {
  return resolveGameKey(gameKey) ?? gameKey.toLowerCase().replace(/_/g, "-");
}

export function getGameDefinition(gameKey: string) {
  const normalizedKey = resolveGameKey(gameKey);
  return normalizedKey ? gameDefinitionByKey.get(normalizedKey) ?? null : null;
}

export function getGameName(gameKey: string) {
  return getGameDefinition(gameKey)?.name ?? gameKey;
}

export function getGameHomeTags(gameKey: string) {
  return getGameDefinition(gameKey)?.homeTags ?? [];
}

export function getGameSuccessfulResultLabel(gameKey: string) {
  return getGameDefinition(gameKey)?.successfulResultLabel ?? "clear";
}

export function buildAlternateGameLinks(currentGameKey: string): GameLink[] {
  const normalizedCurrentGameKey = toRouteGameKey(currentGameKey);

  return supportedGames
    .filter((game) => game.key !== normalizedCurrentGameKey)
    .map((game) => ({
      href: `/games/${game.key}`,
      key: game.key,
      label: `Play ${game.name}`,
    }));
}
